### ISSUE TITLE
About Trees rework

### ISSUE THREAD

**Issue by Tarek-Hasan** [stuntrally/stuntrally3#24]
I don't have an account for new forum, so posting here.
I'm suggesting trying out [Tree It](https://www.evolved-software.com/treeit/treeit). Though only for windows, this free app has many more features than all the app you mentioned in forum post tried for making trees.

[Here](https://lui.gumroad.com/l/qyKQ) is a collection of trees library to use with Tree It. [Preview](https://www.artstation.com/artwork/By4R8)
I also have sample tree library from Tree It author somewhere in my drive. If you are interested, I'll upload those on GDrive later.

If you are planning to make a fantasy themed map you can also try out this blender addon - [Stylized Fantasy Tree Generator](https://rc12.gumroad.com/l/fantasytree).

**Comment by cryham** [comment]
Thanks.
Well if you want to join SR3 forum, info how is in 1st sticky post:
https://groups.f-hub.org/d/2ftpShKs/-how-to-post-sr3-info-help-links-about-etc-

I'm set to using https://github.com/abpy/improved-sapling-tree-generator
Just added info in post. Plus I gathered lots of links for CC-BY models with textures.
I surely won't use Windows only, closed source tools, when we have FOSS alternatives, already inside Blender.
