### ISSUE TITLE
Making Linux binary or AppImage

### ISSUE THREAD

**Issue by cryham** [stuntrally/stuntrally3#25]
I already wrote info on [Ogre forum](https://forums.ogre3d.org/viewtopic.php?t=97231). Some links are there too and 1 suggestion.
So far whatever I do I end up with just segfault at start, with no real info what's wrong.
The issue is not with AppImage but because my binary isn't portable and it can't start.

Seems copying all needed `.so` files from `ldd` output, from my system to new `lib/` dir isn't good.
I looked already at SuperTuxKart, Xonotic, RigsOfRods, speed-dreams*.AppImage, these all work.
But I still don't get which libs should I provide and which not, also should I build on old VM, or build as static, IDK what to do yet. I'm guessing I need to read and consider [all that](https://blog.gibson.sh/2017/11/26/creating-portable-linux-binaries/).
We also had a VM setup for old SR binary builds, maybe worth trying again:
https://github.com/stuntrally/stuntrally/tree/master/dist/linux-archive

I'm also trying with my smaller project [cAmp2](https://github.com/cryham/cAmp2), also no luck:
./cAmp2: ./libc.so.6: version `GLIBC_2.38' not found (required by /usr/lib/libX11.so.6

So anyone having some experience or hints?

**Comment by Calinou** [comment]
> I'm also trying with my smaller project [cAmp2](https://github.com/cryham/cAmp2), also no luck:
./cAmp2: ./libc.so.6: version `GLIBC_2.38' not found (required by /usr/lib/libX11.so.6

This is likely because the binary was built on a Linux distribution that is too new compared to your current distribution. This is why you need to build on an old Linux distribution for the binary to be portable. Typically, the oldest still-supported Ubuntu LTS version is a good baseline for this (currently 20.04).

**Comment by cryham** [comment]
Ah okay, thank you. So I need that VM for building set up.

**Comment by cryham** [comment]
Ok I made a VM from Kubuntu-20.04.6.iso
Followed newly updated [Building.md](https://github.com/stuntrally/stuntrally3/blob/main/docs/Building.md) which now uses this nice python [script](https://github.com/stuntrally/stuntrally3/blob/main/build-sr3-Linux.py) I wrote to build SR3 with deps.
SR3 did build fine there. I can start it, but yeah it's a VM so somewhat starts even, got Gui, don't see map, 10 Fps, whatever.

Then I did this, which copies all needed .so:
`ldd stuntrally3 | awk 'NF == 4 { system("cp " $3 " .") }'`
Got all files back and I'm trying to start on my Debian 12 now:
Got this now, ugh what would that mean?
Inconsistency detected by ld.so: dl-call-libc-early-init.c: 37: _dl_call_libc_early_init: Assertion `sym != NULL' failed!

I guess I copied too many .so? It's like 95 new lib* files from that VM system.
How do I know which should I use from that VM and which should not be here?

**Comment by cryham** [comment]
Ok I'm studying our old [linux-archive](https://github.com/stuntrally/stuntrally/tree/master/dist/linux-archive) scripts. Probably most important here is [copy-libs-linux.sh](https://github.com/stuntrally/stuntrally/blob/master/dist/linux-archive/copy-libs-linux.sh) Though IDK how scrawl did pick those libs and filters for them. I'll try using that. Wonder if other games have any info how to make their linux binary releases.

**Comment by cryham** [comment]
Okay I think I got it running well now.
Tested build from Kubuntu 22.04 on Manjaro kde 23.1.4 in VM
I'll test a couple more distros in VM, and we should have a 3.1 release very soon with Linux binary.
Just need to add some more challenges for new vehicles probably.

![21_16-52-29`s](https://github.com/stuntrally/stuntrally3/assets/720641/ba7b47e0-39c4-41c4-867a-b606b97cad0b)

**Comment by cryham** [comment]
Allright it worked also on clean Ubuntu 23.10, Linux Mint-21.3 and MX Linux 23.2.
With lowest settings I get 10 Fps, kind of possible to drive.

**Comment by cryham** [comment]
SR 3.1 released with Linux binary [here](https://github.com/stuntrally/stuntrally3/releases).
