### ISSUE TITLE
Stunt Rally v3.1 - issue with offline LAN connection

### ISSUE THREAD

**Issue by DukeFreeman** [stuntrally/stuntrally3#28]
In the past we have enjoyed playing Stunt Rally at our LAN parties.

At our last LAN party we wanted to play the new version 3.1, but unfortunately we couldn't get it to work. When creating a listen server from inside the game/main menu, we always get the message that we should check our network settings or routing/firewall settings.

At our LAN parties, everything takes place completely offline without internet or routing. So far this has never been a problem for Stunt Rally.

Can we hope that this issue will be fixed?

Thank you very much in advance. :-)

**Comment by cryham** [comment]
Yes I need to fix this.
At some point I broke multplayer completely I think between SR 3.0 and 3.1.
I tested on same PC and couldn't get a multplayer game to start, it was waiting at loading and I've seen errors in .log from it.

**Comment by DukeFreeman** [comment]
Thank you for your quick response and good luck fixing it :)

**Comment by sirken** [comment]
I've enjoyed SR v2 over LAN with friends, and tried 3.1 today but was unable to get it working on Mint 20. After coming across this thread, I'm assuming it's the same issue. Both server and client can connect to the lobby and see each other, and click Ready, but both crash as the level is loading. From the CLI getting this:

`./stuntrally3.sh: line 21: 2054796 Segmentation fault      (core dumped) "$BINPATH/stuntrally3" $*`

I looked through the log files in ~/.config/stuntrally3/ but didn't see any additional errors. Is there a way to run with debug to see more details?

**Comment by cryham** [comment]
It should be easy to build on Debian like using py sctipt, info here:
https://github.com/stuntrally/stuntrally3/blob/main/docs/Building.md
I just added Config variable there, if you uncomment to this `Config = 'Debug'` it should build Debug too. Then you can use `gdb` or other debugger with that Debug build.

I have a different error with LAN it seems, track loads but both players get stuck on screen with "waiting for other players.." and I see many errors in ogre.log like:
`19:53:40: == Netw GAME_STATUS  WRONG !lobby or !callback`

**Comment by cryham** [comment]
Okay. So I just checked again and it **is** working for me.
I just need to have empty `master_server_address = ` in game.cfg.
I'm testing on same PC, don't really have a way otherwise.

Could you attach or upload your Ogre.log files from both PCs trying to start game, when it fails?
Also do you have ports forwarded? Because best if all players have that (only 1 player can have not). Well if chat works then it should be fine already I think.

Otherwise I don't have a clue. This code didn't change almost at all since years. Only some parts around, possibly could affect.

**Comment by cryham** [comment]
@DukeFreeman @sirken 
Do you still have not working LAN in SR3?
I tested on 1 PC only, but it works for me.

**Comment by cryham** [comment]
Okay I tested on windows 10 and indeed there is an issue, Create or Direct connect don't start, just show 
`<Tag name="NewtworkFailed">Failed to initialize networking. Try different local port and make sure your firewall is properly configured.</Tag>`
which comes from
```
		catch (...)
		{	MsgError(TR("#{NewtworkFailed}"), TR("NetworkError"));
```
Meaning probably it went wrong in here:
```
			app->mClient.reset(new P2PGameClient(this, pSet->local_port));
			app->mClient->updatePlayerInfo(pSet->nickname, sListCar);
```
will need to investigate on Windows then.
It works fine for me on Debian.

**Comment by DukeFreeman** [comment]
Please excuse the late response and thank you very much for taking care of the matter.
Exactly, we had the problem on all Windows 7 and Windows 10 PCs. Everything transparently via LAN (no WAN connection / no routing and no firewalls involved). Unfortunately, our next LAN party is not until the end of November.

**Comment by cryham** [comment]
Okay I found what was wrong.
One line was missing from old SR main.cpp in new SR3, that magically did init memory for enet on Windows and did nothing on Linux.
Next release 3.2 will have it fixed.

**Comment by DukeFreeman** [comment]
Thank you very much for taking care of the issue. Then maybe we can play the new release at our winter LAN. 
I wish you all the best. :)
