### ISSUE TITLE
compiling Stuntrally3 on a Raspberry Pi 5

### ISSUE THREAD

**Issue by arohrbacher** [stuntrally/stuntrally3#29]
Hi,
I am attempting to compile Stuntrally3 on a Raspberry Pi 5 (4 GB Ram, Raspberry Pi OS Bookworm, 4 kByte page size, Wayland) using the procedure outlined in `docs/Building.md`, i.e. using the Python script `build-sr3-Linux.py`. Before running the script I installed all dependencies (as explained in `docs/Building.md`).
When running the script it clones the repositories, creates the build files and then starts to compile. However, after a while an error is thrown:
`ninja: build stopped: subcommand failed.`
Attached a file containing the output just before the error occurs - there are some errors mentioned that I don't know how to deal with
[sr_compile_error.txt](https://github.com/user-attachments/files/16134593/sr_compile_error.txt)
Can anybody help me?
TIA

**Comment by cryham** [comment]
Hi.
This is a low leverl error from OgreNext,
while building or using its internal OgreMain/include/Math/Array/NEON/ at very start.
Please report this issue here:
https://github.com/OGRECave/ogre-next/issues
(like in above post)
I think this has nothing to do with SR3.

**Comment by arohrbacher** [comment]
Hi,
I reported the issue [here](https://github.com/OGRECave/ogre-next/issues/451) and with the help there I was able to resolve the OgreNext issue.

However, I now face a sr3 build issue, please see the attached output from the build attempt:
[sr3_build_failed.txt](https://github.com/user-attachments/files/16165313/sr3_build_failed.txt)

Any idea what's wrong?

Many thanks!

**Comment by cryham** [comment]
Ok done.
So now you would need to update SR3 sources. Probably like so:
```
cd /home/pi/dev/sr3/ 
git pull
```

**Comment by cryham** [comment]
Argh this broke our CI builds. @AnotherFoxGuy could you update OgreNext deps for it? I'm not sure how to fix that.

**Comment by arohrbacher** [comment]
Allright, your change in the sr3 code finally let me build the executable. I followed your instructions above to update the sr3 source and re-ran `build-sr3-Linux.py`
When I start `./stuntrally3` it asks me to select the renderer (only choice is "OpenGL 3+ Rendering Subsystem") and I can select several graphics options. But no matter which settings I choose, the program returns me to the command prompt after clicking "Accept"; these are the messages on the console:
[crash.txt](https://github.com/user-attachments/files/16182351/crash.txt)
Any idea?
Again, many thanks for your help!

**Comment by cryham** [comment]
So the ending is
```
GL_SUN_multi_draw_arrays
Supported GLX extensions: GLX_ARB_context_flush_control GLX_ARB_create_context GLX_ARB_create_context_no_error GLX_ARB_create_context_profile GLX_ARB_fbconfig_float GLX_ARB_framebuffer_sRGB GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_buffer_age GLX_EXT_create_context_es2_profile GLX_EXT_create_context_es_profile GLX_EXT_fbconfig_packed_float GLX_EXT_framebuffer_sRGB GLX_EXT_no_config_context GLX_EXT_swap_control GLX_EXT_swap_control_tear GLX_EXT_texture_from_pixmap GLX_EXT_visual_info GLX_EXT_visual_rating GLX_MESA_copy_sub_buffer GLX_MESA_query_renderer GLX_MESA_swap_control GLX_OML_swap_method GLX_OML_sync_control GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_SGI_make_current_read GLX_SGI_video_sync 
WARNING: GraphicsSystem::deinitialize() not called!!!
Speicherzugriffsfehler
```
Does Speicherzugriffsfehler mean Memory access error? or Storage like SSD/HDD?
Either way this is still early initialization of OgreNext.
I have it like this:
```
**************************************
***   OpenGL 3+ Renderer Started   ***
**************************************
Registering ResourceManager for type GpuProgram
RenderSystem capabilities
-------------------------
RenderSystem Name: OpenGL 3+ Rendering Subsystem
GPU Vendor: amd
```
So the next step in your case that should be `OpenGL 3+ Rendering Subsystem` init and `ResourceManager` too.
I think OgreNext fails here with either reading plugin or resources file or path on drive with this IDK.
I'm not sure if this is a valid OgreNext issue, if @darksylinc wants to investigate?
Question is if OgreNext is supported on Pi5? Is its GPU capable of the shader model used by HLMS?
Would this GPU even be capable of rendering any SR map at acceptable Fps (for me at least 30).
I couldn't find any good benchmark comparison of Pi5 GPU and I'm guessing it's at laptops level integrated GPUs or below? Any idea? I'd say this all is fun but unlikely to work. Not sure.

**Comment by cryham** [comment]
Here is my log up to this point
[Ogre.log](https://github.com/user-attachments/files/16182735/Ogre.log)

**Comment by darksylinc** [comment]
Hi!

The log says the driver is advertising OpenGL 3.1; OgreNext needs at least GL 3.3 + a couple of important extensions (that are usually found in GL 4.0 capable HW). Thus it won't run.

However this sounds odd because I'm no Pi expert but AFAIK VideoCore VII supports Vulkan 1.2.

IIRC SR3 doesn't support Vulkan due to a couple issues (mostly with the GUI); but a VK 1.2 capable HW should support newer OpenGL unless the driver didn't implement it.

Perhaps there is some luck with [Zink](https://blogs.igalia.com/itoral/2020/11/05/v3dv-zink/)? (Zink = OpenGL via Vulkan).

**Comment by AnotherFoxGuy** [comment]
> @AnotherFoxGuy could you update OgreNext deps for SR3? I'm not sure how to fix that.

I can fix that, will open a PR for that soon

**Comment by cryham** [comment]
Ah, since you have built OgreNext already, you could try starting some samples from it.
Should be easier to do and if these work we would know SR3 could too.
There should be many inside:
/Ogre/ogre-next/build/Release/bin/Sample_*

**Comment by darksylinc** [comment]
I took a look at the log again, it seems it's advertising version 3.1 but providing a lot of modern extensions.

It probably advertises 3.1 due to a technically. You MIGHT be able to get it working by removing this line in OgreGL3PlusRenderSystem.cpp:

```cpp
            if( !mDriverVersion.hasMinVersion( 3, 3 ) )
            {
                OGRE_EXCEPT( Exception::ERR_RENDERINGAPI_ERROR,
                             "OpenGL 3.3 or greater required. Try updating your drivers.",
                             "GL3PlusRenderSystem::_createRenderWindow" );
            }
```
and:

```cpp
        if( gl3wRetStatus != GL3W_OK || !mGLSupport->hasMinGLVersion( 3, 3 ) )
        {
            OGRE_EXCEPT( Exception::ERR_RENDERINGAPI_ERROR,
                         "OpenGL 3.3 is not supported. Please update your graphics card drivers.",
                         "GL3PlusRenderSystem::initialiseContext" );
        }
```

But there are no guarantees of whether it will work or it will run or render correctly.

**Comment by cryham** [comment]
Okay thanks for help.
I'm going to close this, as Pi5 being below SR3 / OgreNext HW requirements.
If it started somehow I still doubt it would be usabe for playing SR3 (at decent Fps).
I kind of support Vulkan meaning I do but I don't check it often and not sure if it works or I have to fix it again etc.

**Comment by arohrbacher** [comment]
Hi all for your help so far - much appreciated!
I'll try @darksylinc 's suggestion probably over the weekend when I have more time and report back.

As for the RPi5's capabilities to run Stuntrally, I also tried to run a x64 build of version 1.4 (found [here](https://sourceforge.net/projects/stuntrally/files/1.4/StuntRally-1.4-linux64.tar.xz/download) ) with the use of box64 - this worked surprisingly well with very decent framerates, but the problem was that I could only load one or two tracks; these were apparently smaller than others. If loading larger tracks, I would get a segmentation fault...
Newer Stuntrally versions (x64 builds) I couldn't get to work under box64 - it complains about missing libs...

BTW, I am running Rig of Rods (a x64 build) nicely using box64 - decent fps mostly, just some maps are a little on the low fps side - all-in-all I am happy with how Rig of Rods runs on my RPi5, that's why I also wanted to get Stuntrally working...

Best regards!

**Comment by Calinou** [comment]
Raspberry Pi is an ARM SBC, and most SBCs only support OpenGL ES natively. OpenGL is typically provided via emulation or a very limited subset. On Raspberry Pi, such support was limited for OpenGL 1.x for years (and then OpenGL 2.1). I'm surprised desktop OpenGL 3.1 is even supported on a Raspberry Pi 5 in fact.

**Comment by cryham** [comment]
Rigs of Rods has low requirements, it works on laptops in general.
SR 2 had higher than RoR and over time also higher.
Moving to SR 3 made HW requirements also higher, it's harder to run on laptops.
And since I got a new PC and GPU, SR 3.2 is also getting better graphics while HW requirements.
I try supporting lower specs but there is a limit. Also I did miss some optimizations, still to do.

**Comment by arohrbacher** [comment]
ok, just for completeness sake: I followed  @darksylinc 's suggestion and modified `OgreGL3PlusRenderSystem.cpp`; the build succeeded, but it still errors out, this time with
```
An exception has occured: OGRE EXCEPTION(3:RenderingAPIException): Vertex Program 300000000VertexShader_vs failed to compile. See compile log above for details. in GLSLShader::compile at /home/pi/dev/Ogre/ogre-next/RenderSystems/GL3Plus/src/GLSL/OgreGLSLShader.cpp (line 312)
AL lib: (EE) alc_cleanup: 1 device not closed
```
Attached the complete crash log, if anybody is interested:
[crash.txt](https://github.com/user-attachments/files/16195281/crash.txt)

I guess it's time to give up on Stuntrally3 on a RPi5...

Again, many thanks for the help...

**Comment by cryham** [comment]
GLSL compile log: 300000000VertexShader_vs
0:2(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES
Same issue as before, but for compiling first shader.
Yeah probably have to give up IDK.

**Comment by Calinou** [comment]
>  And this is sad, as we have 8192 skies only now, could fix but meh.

You could downsize textures on load if they exceed the maximum supported texture size.

**Comment by darksylinc** [comment]
As a semi-passive observer of this thread, it looks like the Pi5 should perfectly capable of running SR3 (perhaps with some compromises) but the question is how much resources can be dedicated to such support (i.e. get a Pi5, get Vulkan running stable, workarounding stuff like texture limits).

**Comment by cryham** [comment]
Resources? Hmm, none, from my side. If that's what you're asking.
Maybe a little time to get Vulkan, since it did work better on Windows with integrated GPU on laptop, at least in one case.
I certainly won't buy Pi5, I don't even have a Windows+NVidia setup to test if it still works fine. I rarely test performance on my parent's Debian PC will lower spec GPU.
I dropped texture size option, since I don't want to have doubled files for other size(s). If there was an easy option in OgreNext to load textures up to set size or downscale all textures on loading, I would add it.

Getting SR3 to work on low spec HW was never my goal. And like I said, since I bought a new PC and GPU, I want to make SR3: first look as good as SR2 did (wind and water refraction are finally coming, but still many bugs), SSAO and HDR were once available. And then even better (new HDR, perhaps try GI someday). I I endure fighting with getting that to work, while still having option to use previous compositor etc).

**Comment by arohrbacher** [comment]
Hi all,

I hope it is OK if I post this here, but since it's apparently a lot of work to get SR3.x to run on an RPi5, I instead tried to compile the older Stuntrally 2.7 on my RPi5 - this worked actually pretty well (after collecting all the dependencies) and the performance is pretty good - mostly 20-40 fps (see screenshot - I had to reduce the graphics preset to "middle"):
![stuntrally2 7_rpi5](https://github.com/user-attachments/assets/461c1fc7-fdb9-488a-8411-1952be4c1e68)

There are a few issuses (no dealbreakers, though):
- the in-game map doesn't seem to work - it doesn't show the track
- the textures for tires, lights, and windows of the cars are just white
- after quitting/ending a race and then selecting an other track in the menu, the program quits to the command line; I can load and play this other track after starting the stuntrally again

All tracks I tried are working (some with lower fps); altogether Stuntrally 2.7 is _very_ playable on an RPi5!

Many thanks for creating this - I am happy :smiley:

**Comment by cryham** [comment]
Okay sounds like SR 2.7 is working fine indeed.
I suspect that minimap and shader and some car materials didn't compile for some reason maybe limits of Pi5 GPU. Should be visible in ogre.log or console. But if it's so, then I don't think it could be fixed.
Minimap looks a bit like missing texture, but just guessing, could be shader too.

**Comment by cryham** [comment]
There is a section in game.cfg file, where you can adjust simulation quality. I just added this in SR3 very recently to GUI.
So you could use low to possibly more Fps by less CPU use by simulation:
```
[ sim ]
bullet_freq = 80.000000
bullet_iter = 12
dynamics_iter = 30
game_freq = 80.000000
```
or for medium:
```
bullet_freq = 120.000000
bullet_iter = 18
dynamics_iter = 45
game_freq = 120.000000
```
