### ISSUE TITLE
Can't compile mygui-next

### ISSUE THREAD

**Issue by Poomex** [stuntrally/stuntrally3#3]
Hi, I have successfully compiled Ogre and placed it in the a folder, next to the mygui-next folder. However, when I try to compile mygui-next it complains about the lack of `OgreBuildSettings.h` in `/Ogre/ogre-next/OgreMain/include`.

I tried to copy this file from [here](https://github.com/OGRECave/ogre/blob/master/CMake/Templates/OgreBuildSettings.h.in) but unfortunately, it still errors out. 

Attached are log files from build with OgreBuildSettings.h from the link and without.

[without OgreBuildSettings.h.log](https://github.com/stuntrally/stuntrally3/files/10899719/without.OgreBuildSettings.h.log)
[with OgreBuildSettings.h from templates.log](https://github.com/stuntrally/stuntrally3/files/10899720/with.OgreBuildSettings.h.from.templates.log)

**Comment by cryham** [comment]
Hi, thanks for testing.
I have OgreBuildSettings.h inside paths:
```
/Ogre/ogre-next/build/RelWithDebInfo/include
/Ogre/ogre-next/build/Release/include/
/Ogre/ogre-next/build/Debug/include/
```
`OgreBuildSettings.h` is something I think that gets generated by CMake, it will change when CMake options change.
IIRC I copied the `/Ogre/ogre-next/build/include/OgreBuildSettings.h` file after build or CMake run to each path of above.
I also have `OgreGL3PlusBuildSettings.h` and `OgreVulkanBuildSettings.h` in all those paths, but I didn't copy them.

**Comment by Tarek-Hasan** [comment]
Hey @cryham,
I'm just curious. Why fork an outdated fork of MyGUI to use in StuntRally, instead of using the [original MyGUI](https://github.com/MyGUI/mygui) project?

**Comment by cryham** [comment]
Well my fork was based on other fork that worked with OgreNext 2.1 or so, but some years ago. We did manage to get it work for latest OgreNext 3.0 and that's what I needed.
I didn't have the time or any real need yet to go into upmerging it to meet latest MyGui from git version. Could be some trouble. IDK, didn't yet try.

**Comment by cryham** [comment]
There is a newer way of building on Linux, here
https://github.com/stuntrally/stuntrally3/blob/main/docs/Building.md
using a script https://github.com/stuntrally/stuntrally3/blob/main/build-sr3-Linux.py
that does all needed.
I'm closing, this is an old issue, outdated.
