### ISSUE TITLE
Crash when setting triplanar level to "3 Normal" for standard or horizon terrain

### ISSUE THREAD

**Issue by Calinou** [stuntrally/stuntrally3#30]
**OS:** Windows 11 23H2
**Version:** Stunt Rally 3.1

When setting the triplanar level to "3 Normal" for standard or horizon terrain in the settings menus, the game crashes with a shader compilation error the next time it tries to load a track (e.g. press <kbd>F5</kbd> after changing the setting).

**Comment by cryham** [comment]
It's one of those options marked as "= todo, not done" or buggy.
Didn't expect crash though. Could you attach `ogre.log`?
But yeah anyway, triplanar normal has a bug, reported on Ogre forum, not fixed, IDK how.

In case of shader errors:
The next step (very optional) would be enabling in `game.cfg`
```
debug_properties = on
debug_shaders = on
```
Finding out the last line in ogre.log saying which shader failed and attaching that file too.

**Comment by cryham** [comment]
I have hidden this option from Gui for now. There is a lot of issues on forum to deal with first. So I leave this is for later.

**Comment by cryham** [comment]
I'm closing this, not an option anymore.
Can find it by "TerTripl", it's the Gui name
There are plenty of such issues, on Roadmap.md, IMO no need to have in issues too.
