### ISSUE TITLE
Stunt Rally 3.2 Windows 11 installer, compiled as 32-bit, not 64,

### ISSUE THREAD

**Issue by xga-cga** [stuntrally/stuntrally3#34]
** General Help **
For crashes and more info, please include `Ogre.log` or `Ogre_ed.log` for editor.

Useful docs pages: [Troubleshooting](https://github.com/stuntrally/stuntrally3/blob/main/docs/Troubleshooting.md#what-we-will-ask-from-you), settings and logs [Paths](https://github.com/stuntrally/stuntrally3/blob/main/docs/Paths.md), [Running](https://github.com/stuntrally/stuntrally3/blob/main/docs/Running.md), forum [topic](https://groups.f-hub.org/d/2ftpShKs).

**Describe the issue**
What happens, what was expected
StuntRally-3.2-installer.exe
installs to c x86 directory in Windows, not 64-bit executable.
...

**How to Reproduce**
Steps to reproduce this behavior
...

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro, 64-bit
 - Game Version: 3.2 Windows Installer official release

**Comment by xga-cga** [comment]
Maybe someone could do a stand-alone zip file of 64-bit version for Windows, or it's been done in the past, so you or others don't have to re-compile or release new installer.  Thanks for your time and hard work.

**Comment by cryham** [comment]
Thanks, I didn't test on Windows 11, but I'm a bit confused.
Is the problem that SR exe is built as 32bit not 64 or that it is installed into Program FIles x86 not x64?
Does it work anyway on Windows 11 or does it not start because of this?

**Comment by xga-cga** [comment]
It works on 64-bit Windows 11 pro and installs correctly the way that 32-bit programs have.  By default 32-bit programs install into 
![2024-10-14 15_06_04-Stunt Rally 3 2 Setup](https://github.com/user-attachments/assets/c8f6da35-91f9-462d-b8ae-c20ae3ecd208)

I had mistakenly thought there was a 64-bit  version of Stunt Rally 3 in the past.   Thanks for the clarification, I may have had it confused with another game.

**Comment by cryham** [comment]
Just verified, and SR 3.2 (also 3.1) exe is 64-bit, both for game and editor.
I didn't change building in 3.2, it was 64-bit in 3.1 too.
The only issue is that SR installs in Program Files x86\. I should install in Program Files\.
