### ISSUE TITLE
Any chance to get an macOS version too?

### ISSUE THREAD

**Issue by LinuxDonald** [stuntrally/stuntrally3#36]
Any chance to get an macOS/arm version too?

**Comment by cryham** [comment]
So macOS - no likely never from my side. I wrote more in [Faq](https://github.com/stuntrally/stuntrally3/blob/main/docs/Faq.md#os).
I'm okay if someone does this in PR. But that didn't happen in over 10 years, so again: very unlikely.

As for arm - I have no idea how to even do it.
And I have like always a ton of tasks/issues planned which I know how to start and I'd like to soon.
