### ISSUE TITLE
Strong graphics issues on Windows

### ISSUE THREAD

**Issue by BSoD38** [stuntrally/stuntrally3#37]
**Describe the issue**
Certain effects have some graphics issues, such as checkerboard patterns on headlights, crystals, etc.

I tried changing between Vulkan and OpenGL, and the result is the same. I'm not sure if it's actually changing anything though, as the game's video settings always reports "OpenGL 3.3+".

**How to Reproduce**
Start the game on the "Slide" map. You will immediately see the graphics bugs.

**Screenshots**
![image](https://github.com/user-attachments/assets/72cb1d21-0965-4116-ab02-4f6555b4eb82)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version: 3.2
 - GPU: RTX 4090 (latest driver)
 - CPU: i9-13900K

**Comment by cryham** [comment]
I know this, it's the depth buffer garbage thing.
Could you try same track but with disabled Refractions on Water options tab? Restarting game after changing.

**Comment by cryham** [comment]
This should now be fixed in latest git. As I reworked the compositor and it copies depth buffer first then writes to it, not at the same time. I didn't see those issues after rework.

**Comment by cryham** [comment]
-
