### ISSUE TITLE
Select boxes don't work in the UI

### ISSUE THREAD

**Issue by BSoD38** [stuntrally/stuntrally3#38]
**Describe the issue**
Dropdown select boxes simply do not work in the menus on Windows. Nothing happens when clicking them.

**How to Reproduce**
Start the game and try to click on any select box. Nothing will happen.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Game Version: 3.2

**Comment by Calinou** [comment]
Did you click the text or the arrow on the right? It works for me if I click the arrow on the right, but not the text. It's a MyGUI issue, I guess.

**Comment by cryham** [comment]
Or you can click it and then use mouse wheel.
I think it has been like so since the start in MyGUI.

**Comment by cryham** [comment]
wow, it was actually fixable, took so long
