### ISSUE TITLE
Segmentation fault on startup

### ISSUE THREAD

**Issue by lrustand** [stuntrally/stuntrally3#4]
I was able to build it after a lot of trouble, but when starting the game it segfaults in the initial loading screen when loading terrain. The segfault happens on line 543 in `src/Terra/Hlms/OgreHlmsTerra.cpp`:

```
constBufferSlot += mAtmosphere->bindConstBuffers( commandBuffer, constBufferSlot );
```

Core file was too big to upload on github so uploaded it here: https://0x0.st/HKGj.zip

The MyGUI log also shows a missing texture called SX.jpg as the last line of the log.

[MyGUI.log](https://github.com/stuntrally/stuntrally3/files/11353661/MyGUI.log)
[Ogre.log](https://github.com/stuntrally/stuntrally3/files/11353664/Ogre.log)

**Comment by cryham** [comment]
Okay great that you've built it.
Do you have set in 'Ogre/ogre-next/build/CMakeCache.txt' those components:
```
OGRE_BUILD_COMPONENT_ATMOSPHERE:BOOL=ON
...
OGRE_BUILD_COMPONENT_PLANAR_REFLECTIONS:BOOL=ON
```
Looks like I didn't add this to guide.
If not then set both to ON and then it needs to go the long way: rebuild Ogre, then MyGui and lastly SR3.
But if you already had ON in both, we have a different issue, not sure yet what.

**Comment by lrustand** [comment]
Ok, great. I had already set the planar reflections to be able to build, but it did not work anyway so I actually had to remove the block of code that used it from SR. I did not rebuild MyGUI after enabling planar reflections so that might be the reason it didn't work the first time.

I will try again with your above instructions.

I also have the file `Media/cars/_previews/SX.jpg`, so not sure why it didn't find it.

**Comment by lrustand** [comment]
Thanks, now it worked!

But I was just booted into a test map and am unable to access the menu. When pressing escape the game exits. I realize the game is still in development, but the readme said that it was playable in single player modes. Is this how it is supposed to be at the moment or am I experiencing a bug?

**Comment by lrustand** [comment]
Ok, never mind. The menu is on tab...

**Comment by cryham** [comment]
Cool. I'm glad it works.
