### ISSUE TITLE
Unix desktop files missing

### ISSUE THREAD

**Issue by AsciiWolf** [stuntrally/stuntrally3#41]
https://github.com/stuntrally/stuntrally/blob/master/dist/stuntrally.desktop
https://github.com/stuntrally/stuntrally/blob/master/dist/sr-editor.desktop

These desktop files for Stunt Rally seem to no longer be a part of this repo.

Please, consider re-adding them.

**Comment by cryham** [comment]
Added, used 3 in exec, SR3 name filename.

**Comment by AsciiWolf** [comment]
https://github.com/stuntrally/stuntrally/blob/master/CMakeLists.txt#L92
https://github.com/stuntrally/stuntrally/blob/master/dist/CMakeLists.txt

**Comment by AsciiWolf** [comment]
Also, are you sure you are installing [stuntrally.png](https://github.com/stuntrally/stuntrally3/blob/main/data/gui/stuntrally.png) and [sr-editor.png](https://github.com/stuntrally/stuntrally3/blob/main/data/gui/sr-editor.png) into /`share/icons/hicolor/512x512/apps/`?

**Comment by cryham** [comment]
Added in https://github.com/stuntrally/stuntrally3/commit/f3b230215e4a99f1c01f6eda1f7d938e2932e388
Yeah I'm not sure about anything here and in dist/ that's why I didn't add it from old SR dir, didn't know what it is needed for. I also never did `make install` or such. I'm glad you're keeping an eye on this.

**Comment by AsciiWolf** [comment]
Thanks. :-) One more thing: I did not test this yet, but shouldn't the dist directory also be added to the main CMakeLists.txt file like [it was](https://github.com/stuntrally/stuntrally/blob/master/CMakeLists.txt#L92) in the old stuntrally v2 repo?
