### ISSUE TITLE
Racing wheel support

### ISSUE THREAD

**Issue by lrustand** [stuntrally/stuntrally3#5]
In Stuntrally 2 I used to use my G27 racing wheel to play. In Stuntrally 3 this is not recognised as an input, when trying to assign it to any control in settings the game doesn't register any of the axes.

I have tested the wheel with jstest and all the axes and buttons are recognised in the OS.

**Comment by cryham** [comment]
Right. It is still on my to do list to restore it.

**Comment by lrustand** [comment]
Sweet, it works! That was very fast delivery!

**Comment by cryham** [comment]
Great

**Comment by ThreeDeeJay** [comment]
Any chance Windows will ever get force feedback? 👀 
https://github.com/stuntrally/stuntrally3/blob/b452c4376cc1a99ab0be3df93df19d3a5b49b37f/src/vdrift/forcefeedback.h#L4

**Comment by cryham** [comment]
It's not supported on Linux either. This is just a comment from VDrift's code.
I don't have a wheel or device with force feedback, to implement it, so it was and is lowest priority for me.

**Comment by ThreeDeeJay** [comment]
Fair enough 👌
